packages/delisp-core/src/infer.ts, packages/delisp-core/src/types.ts, packages/delisp-core/src/unify.ts
This will allow us to introduce new type operators easily without
having to change the recursion mechanism of the type inference for
example.
=> Replace -> type with general type application

packages/delisp-core/__tests__/reader.ts, packages/delisp-core/src/reader.ts
Added breaking test case: `a2` results in a symbol with name `a`.
=> FIX: Reader not parsing Symbol correctly

packages/delisp-core/__tests__/readModule.ts, packages/delisp-core/__tests__/reader.ts, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/index.ts, packages/delisp-core/src/parser-combinators.ts, packages/delisp-core/src/reader.ts, packages/delisp-core/src/syntax.ts
- Add a new `Module` type (wrapping `Syntax[]`) 
- Add `readAllFromString` in reader, consuming the full input and returning `ASExpr[]`
- Add `readModule` in the top level (combining the above 2 to do `string -> ASExpr[] -> Syntax[] -> Module`)
- Update compiler to ~accept both `Syntax` and `Module` as input~ also compile Modules
Fixes #9
=> Module reading and compiling

packages/delisp-core/__tests__/eval.ts, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/compiler/__snapshots__/jsvariable.spec.ts.snap, packages/delisp-core/src/compiler/jsvariable.spec.ts, packages/delisp-core/src/compiler/jsvariable.ts, packages/delisp-core/src/reader.ts
To understand the issue, consider how the test case was compiled:
```lisp
((lambda (x)
((lambda (y) x) 11))
33)
```
compiled to
```javascript
(function (p1) {
(function (p1) {
return p1
})(11)
})(33)
```
So it is important for the compiler not to accidentally shadow variables in the generated code.
By introducing `varnameToJS`, and the injective property we'll require,  target JS variables will only shadow if the variables also shadow in the source.
=> Fix compiler in the compilation of nested lambda functions

packages/delisp-core/__tests__/compiler.ts
if a valid expression is passed to compilerError, the test will fail.
=> Make the compiler tests fail on unexpected success

packages/delisp-core/src/compiler.ts, packages/delisp-core/src/compiler/inline-primitives.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/utils.ts, packages/delisp-runtime/src/primitives.ts
**To merge after #24 and #25**
This pull request introduces compilation of inline primitives. For example, `(+ x 2)` will be compiled as ` x + 2`.
When used _not_ of a function call, a wrapper function will be added, so they can be used as first-class values, For example, `(map +)` generates:
```javascript
env["map"]((x0, x1) => x0 + x1);
```
=> Inline compilation

packages/delisp-core/__tests__/read-module.ts, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/convert-type.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/error-report.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax.ts, packages/delisp-core/src/unify.ts, packages/delisp-core/src/utils.ts, packages/delisp/src/repl.ts
This pull request aims to improve the reporting of type errors, but even more, improve the infrastructure to improve them more in the future.
The changes consist mainly of:
In future PRs, error reporting can be improved further, by it requires a bit of research.
- The solver can use some heuristics to decide in which order to solve the constraints.
- All errors can be collected, not just the first one.
- Error cascading can be avoided.
We can look at how Elm does its excellent error reporting.
=> WIP - Improve type errors

packages/delisp-core/src/compiler.ts, packages/delisp-core/src/compiler/definitions.ts, packages/delisp-core/src/eval.ts
`staticDefinition` handles definition compilation for batch mode.
`dynamicDefinition` handles definition compilation for the REPL.
=> Implement static and dynamic definitions compilation

packages/delisp-core/src/compiler/inline-primitives.ts, packages/delisp-core/src/convert-type.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/type-utils.ts, packages/delisp-core/src/types.ts, packages/delisp-runtime/src/primitives.ts
- Add `[1 2 3]` syntax to the pretty printer (currently this was being rewritten as `(vector 1 2 3)`)
- Add `[a]` syntax for vector types (both for reading and output)
=> Use bracket notation for vectors

packages/delisp-core/__tests__/__snapshots__/compiler.ts.snap, packages/delisp-core/__tests__/__snapshots__/printer.ts.snap, packages/delisp-core/__tests__/eval.ts, packages/delisp-core/__tests__/infer.ts, packages/delisp-core/__tests__/printer.ts, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax.ts
Support for lambdas with multiple forms
```lisp
(lambda (x)
(print x)
(print x))
```
=> Multiform lambda

packages/delisp-core/__tests__/infer.ts, packages/delisp-core/src/__snapshots__/convert-type.spec.ts.snap, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax.ts, packages/delisp-core/src/type-utils.ts, packages/delisp-core/src/types.ts, packages/delisp-core/src/unify.ts
Introduce type annotations with the syntax
```scheme
(the TYPE EXPR)
```
During type inference, this form will introduce an explicit constraint.  However, note that we do not want to allow user-provided type annotations to generalize inferred types.
For instance, the second form in here should fail:
```scheme
(define string-id
(the (-> string string)
(lambda (x) x)))
(the (-> a a) string-id)  ??
```
This is solved by introducing `rigid/user-specified type variables`.  Those variables *unify only with themselves* (and normal variables),  but not with constants.
e.g:  `unify(rigid a, string) fails`
That avoids the undesired behaviour above.
=> Type annotations

packages/delisp-core/__tests__/unify.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/unify.ts
This currently breaks the unification process:
```lisp
(+ 1)
```
Result: `TypeError: Cannot read property 'type' of undefined` (when trying to unify `b`).
- Minimal change needed is to explicitly check if `t1` or `t2` are `undefined`, and report it as a `unify-mismatch-error` (with `void`). This prevents the compiler from crashing completely.
- To improve, I added a `unity-missing-value-error` to differentiate between actual mismatches with `void`, for example in `(+ 1 (print "hi")`)
- Updated unification of `application` a bit to first unify the input arguments, then unify the return value separately. This improves error messages and is needed to handle multiple return values properly in the future.
=> Fix error when application arity does not match

packages/delisp-core/__tests__/__snapshots__/printer.ts.snap, packages/delisp-core/__tests__/printer.ts, packages/delisp-core/src/printer.ts
Bit of a crude implementation, but it checks if there was more than 1 `\n` character in between expressions, and adds a single empty line in the output. This allows grouping of lines (while disallowing multiple empty lines in succession): 
```
(define foo 1)
(define bar 2)
(define baz 3)
```
=> Update printer to preserve empty lines

packages/delisp-core/src/compiler.ts, packages/delisp-core/src/compiler/modules.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax.ts
- Updated export syntax from `(export name val)` to `(export sym)`
- Added a `moduleFormat` to the compiler `Env`
- Moved the old compileExport code to a `cjs` ModuleBackend
- Created a `esm` ModuleBackend
- To use the esm backend, run `ESM=1 delisp compile file.dl`
=> ESM exports

editor/emacs/delisp.el, packages/delisp-core/__tests__/__snapshots__/compiler.ts.snap, packages/delisp-core/__tests__/__snapshots__/printer.ts.snap, packages/delisp-core/__tests__/compiler.ts, packages/delisp-core/__tests__/eval.ts, packages/delisp-core/__tests__/infer.ts, packages/delisp-core/__tests__/printer.ts, packages/delisp-core/__tests__/unify.ts, packages/delisp-core/jest.config.js, packages/delisp-core/package.json, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/convert-type.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/index.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/module.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax-utils.ts, packages/delisp-core/src/syntax.ts, packages/delisp-core/src/type-substitution.ts, packages/delisp-core/src/type-utils.ts, packages/delisp-core/src/types.ts, packages/delisp-core/src/unify.ts, packages/delisp-core/tsconfig.build.json, packages/delisp-core/tsconfig.json, packages/delisp/src/cmd-infer-type.ts, packages/delisp/src/cmd-repl.ts, packages/delisp/tsconfig.json, packages/tsconfig.json, tslint.json
Syntax:
```lisp
(type Person {:name string :age number})
```
A lot of changes and refactoring going on here. To guide you through the changes:
- Introduce type `tUserDefined`, different from type variables.
- Capitalized symbols are read as user defined types. (`Person` vs `a`).
- `inferModule` gathers type alias definitions and build an `InternalEnvironment`.
- This is passed to `unifyInEnvironment`.
- `unify` will consider user defined types as equal to their definition.
Type aliases can't be propagated as I expected. Consider
```lisp
(type ID number)
(if true (the ID 5) 3)
```
The type of the second `if` is "ambiguosly" ID or number. And indeed it gets more complex so I think there is no easy way to propagate it.  
**Does it invalidate the whole approach???** It could be... but this …
=> Implement type aliases

packages/delisp-core/__tests__/__snapshots__/compiler.ts.snap, packages/delisp-core/__tests__/compiler.ts, packages/delisp-core/__tests__/eval.ts, packages/delisp-core/__tests__/infer.ts, packages/delisp-core/__tests__/printer.ts, packages/delisp-core/src/convert.ts
Changes the let-bindings syntax from
```
(let ((x 1)
(y 2)
(z 3))
body)
```
into using a map:
```
(let {x 1
y 2
z 3}
body)
```
=> Use map for let bindings

packages/delisp-core/__tests__/infer.ts, packages/delisp-core/__tests__/unify.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/syntax.ts, packages/delisp-core/src/type-utils.ts, packages/delisp-core/src/unify.ts
Implement expansion of internal (defined in the module) type aliases before unification.
Unknown type aliases, like those returned by other modules, they are considered user-defined proper types , instead of aliases, so they only unify with themselves.
That means:
`(the ID number)`
works locally in the same module as a number. But if you export a function
`(define make-id (lambda (x) (the ID x)))`
then the returned ID will be considered a blackbox type by other modules. So that is a smart constructor.
=> Type alias expansion and user-defined data types

packages/delisp-core/__tests__/__snapshots__/compiler.ts.snap, packages/delisp-core/__tests__/__snapshots__/reader.ts.snap, packages/delisp-core/__tests__/reader.ts, packages/delisp-core/src/reader.ts
The reader considers `1a` to be a valid number (1) followed by a valid symbol (a). We should either detect this as an invalid number/symbol, or allow it and parse it completely as a single symbol.
=> Fix reading symbol starting with number

packages/delisp-core/__tests__/printer.ts
Adds some test cases ensuring that the prettyPrinter only modifies spaces/newlines, not the notation of the input code.
This currently fails for
- Partial type annotations: `_` is transformed into `__t1`
- At-expressions: `@foo{...}` is transformed into `(foo ...)`
=> Add prettyPrinter string identity test (after stripping spaces)

packages/delisp-core/__tests__/printer.ts, packages/delisp-core/src/convert-type.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax-utils.ts, packages/delisp-core/src/syntax.ts, packages/delisp-core/src/type-wildcards.ts
Ensure the type wildcards are expanded during type inference of type annotations, not during conversion.
This fixes #68
=> Pretty print type annotations including wildcards

packages/delisp-core/__tests__/read-module.ts, packages/delisp-core/__tests__/syntax-locator.ts, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/module.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax-utils.ts, packages/delisp-core/src/syntax.ts, packages/delisp-core/src/typescript-generation.ts, packages/delisp/src/cmd-repl.ts
- Replaces `SVariableReference` completely
- Replaces `SVar` (alias for `string`) in most cases, so we have access to the location of identifiers.
=> Add Identifier to syntax

editor/emacs/delisp.el, packages/delisp-core/__tests__/__snapshots__/compiler.ts.snap, packages/delisp-core/__tests__/__snapshots__/printer.ts.snap, packages/delisp-core/__tests__/compiler.ts, packages/delisp-core/__tests__/eval.ts, packages/delisp-core/__tests__/infer.ts, packages/delisp-core/__tests__/printer.ts, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax-utils.ts, packages/delisp-core/src/syntax.ts
This pull request introduces a new special form `do`.
It works like
```lisp
(do
form1
form2
...
form_n)
```
The form evaluates to the last value. The value of all the forms from 1 to n-1 are ignored. But they are still evaluated.
This is useful together with effectful code, so it can be used in places like `if`:
```lisp
(if true
(do
(print "foo")))
...)
```
=> Support for `do` blocks

editor/emacs/delisp.el, packages/delisp-core/__tests__/__snapshots__/printer.ts.snap, packages/delisp-core/__tests__/infer.ts, packages/delisp-core/__tests__/printer.ts, packages/delisp-core/src/__snapshots__/convert-type.spec.ts.snap, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/compiler/modules.ts, packages/delisp-core/src/convert-type.spec.ts, packages/delisp-core/src/convert-type.ts, packages/delisp-core/src/convert-utils.ts, packages/delisp-core/src/convert.ts, packages/delisp-core/src/eval.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax-utils.ts, packages/delisp-core/src/syntax.ts, packages/delisp-core/src/type-printer.ts, packages/delisp-core/src/types.ts, packages/delisp-runtime/src/index.ts, packages/delisp/init.dl, packages/delisp/package.json, packages/delisp/src/cmd-repl.ts, packages/delisp/tsconfig.json
This pull request implements polymorphic variants on top of the rows that the record system introduced.
The syntax introduced here is temporary. It is clumsy and it has important limitations. For example, it does not support enumeration types (without associated value).
Variant types are described with the operator `or`:
`(or {:version number :unreleased string})`
means a **choice** of the labels `:version` (with a number),  or `:unreleased` with a string value.
Two special forms were introduced:
- `tag`, tag a value with a label, producing an open variant.
```
(the (or {:version number | α})
(tag :version 0))
```
The general for of tag is `(tag LABEL <expression>)`.
- `match` to dispatch a variant based on the value:
```
(match x
({:version number}   number)
({:unreleased _) -1)
```
The …
=> Implementation of polymorphic variants

packages/delisp-core/__tests__/eval.ts, packages/delisp-core/__tests__/infer.ts, packages/delisp-core/src/compiler/inline-primitives.ts, packages/delisp-core/src/infer-debug.ts, packages/delisp-core/src/infer-solver.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/type-printer.ts, packages/delisp/init.dl
Modify lenses to work with the type signature `(-> x _ (values a (-> b _ y)))`
This means that lenses can be used as functions directly. In that case, the primary value gets returned so they act as simple selectors.
`(:x {:x 50})`
=> Modified lenses

examples/test-todo.js, packages/delisp-cli/lib/prelude.dl, packages/delisp-cli/src/cmd-repl.ts, packages/delisp-cli/src/module.ts, packages/delisp-core/__tests__/__snapshots__/convert.ts.snap, packages/delisp-core/__tests__/__snapshots__/printer.ts.snap, packages/delisp-core/__tests__/eval.ts, packages/delisp-core/__tests__/infer.ts, packages/delisp-core/__tests__/read-module.ts, packages/delisp-core/src/compiler.ts, packages/delisp-core/src/compiler/inline-primitives.ts, packages/delisp-core/src/eval.ts, packages/delisp-core/src/index.ts, packages/delisp-core/src/infer.ts, packages/delisp-core/src/printer.ts, packages/delisp-core/src/syntax-convert.ts, packages/delisp-core/src/syntax-functions.ts, packages/delisp-core/src/syntax-utils.ts, packages/delisp-core/src/syntax.ts, packages/delisp-runtime/src/index.ts, packages/delisp-runtime/src/primitives.ts, packages/delisp-runtime/src/string.ts, packages/delisp-runtime/src/vector.ts
This pull request implements an implicit `*context*` parameter which gets passed through the function calls automatically, providing a similar functionality to special variables, dynamic bindings or readers in other languages.
Otherwise of being passed automatically, `*context*` can be used as an ordinary variable. You can rebind it with `let`, and it will be part of the type signature of the functions.
=> Support implicit *context* parameter
